name: test workflow

on:
  push:
    branches:
      - "main"
      - "4-publish-docker-image-on-dockerhub"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: login to ghcr    
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GHCR_TOKEN }} 
