name: test workflow

on:
  push:
    branches:
      - "main"
      - "4-publish-docker-image-on-dockerhub"

jobs:
  any_name:
    runs-on: ubuntu-latest
    steps:
      - name: test echo
        shell: bash
        run: |
          echo "hi"
